apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-postgres
  template:
    metadata:
      labels:
        app: ticket-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine # Imagem Alpine leve
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.database.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.database.name }}"
---
apiVersion: v1
kind: Service 
metadata:
  name: postgres-service
spec:
  selector:
    app: ticket-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
